services:
  web:
    image: registry.luhcaran.fr/atdispo_web:0.1.2
    container_name: atdispos-web
    restart: unless-stopped
    environment:
      MODE_DEV: true
      DB_HOST: db
      DB_USERNAME: ...
      DB_PWD: ...
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.atdispos.rule=Host(`atdispo.luhcaran.fr`)
      - traefik.http.routers.atdispos.entrypoints=websecure
      - traefik.http.routers.atdispos.tls.certresolver=letsencryptresolver
      - traefik.http.services.atdispos.loadbalancer.server.port=80
    depends_on:
      - db
    networks:
      - web
      - atdispos_internal

  db:
    image: registry.luhcaran.fr/atdispo_db:v0.1.1
    container_name: atdispos-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ...
      MYSQL_DATABASE: AtDispo
      MYSQL_USER: ...
      MYSQL_PASSWORD: ...
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - atdispos_internal

volumes:
  db_data:

networks:
  web:
    external: true
  atdispos_internal: